version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crypto-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: Cripto_db
      MYSQL_USER: crypto_user
      MYSQL_PASSWORD: userpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Cripto_db.sql:/docker-entrypoint-initdb.d/01-schema.sql

  api:
    build: .
    container_name: crypto-api
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Cripto_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: crypto_user
      SPRING_DATASOURCE_PASSWORD: userpass123
      JWT_SECRET: SuperSecretKey2024ForCryptoTrading
    ports:
      - "8080:8080"

volumes:
  mysql_data:
